# Generated by Django 4.1.7 on 2023-04-18 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GfMainroute',
            fields=[
                ('rt_main', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('rt_desc', models.CharField(max_length=40)),
                ('rt_section_fg', models.CharField(max_length=1)),
                ('rt_max_insection', models.IntegerField()),
            ],
            options={
                'db_table': 'gf_mainroute',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GfRoutecode',
            fields=[
                ('rt_code', models.CharField(max_length=8)),
                ('routecode_id', models.AutoField(primary_key=True, serialize=False)),
                ('rt_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('s_std', models.IntegerField(blank=True, null=True)),
                ('g_std', models.IntegerField(blank=True, null=True)),
                ('rt_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('rt_spec', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gf_routecode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GfSemi',
            fields=[
                ('semi_code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('semi_desc', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'gf_semi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GfStockcode',
            fields=[
                ('stockgroup', models.CharField(blank=True, max_length=100)),
                ('stockcode', models.CharField(max_length=19)),
                ('stockdesc', models.CharField(blank=True, max_length=300, null=True)),
                ('unit_qty', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_volume', models.CharField(blank=True, max_length=100, null=True)),
                ('std_wt_gm', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('std_pr_bt', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True)),
                ('std_pr_us', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('std_sale_bt', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('std_sale_us', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('std_lb_bt', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('std_lb_us', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('std_unit', models.CharField(blank=True, max_length=1, null=True)),
                ('mt_metal', models.CharField(blank=True, max_length=100)),
                ('eng_desc', models.CharField(blank=True, max_length=500, null=True)),
                ('eng_unit_qty', models.CharField(blank=True, max_length=50, null=True)),
                ('eng_unit_volume', models.CharField(blank=True, max_length=50, null=True)),
                ('max_stock', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_stock', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reorder', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order_time', models.IntegerField(blank=True, null=True)),
                ('old_code', models.CharField(blank=True, max_length=19, null=True)),
                ('maxmin_fg', models.CharField(blank=True, max_length=1, null=True)),
                ('stock_status', models.CharField(blank=True, max_length=1, null=True)),
                ('keep_stock', models.CharField(blank=True, max_length=1, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('purchase_fg', models.CharField(blank=True, max_length=1, null=True)),
                ('cus_id', models.CharField(blank=True, max_length=100)),
                ('account_type', models.CharField(blank=True, max_length=1, null=True)),
                ('std_lb_time', models.IntegerField(blank=True, null=True)),
                ('lb_remark', models.TextField(blank=True, null=True)),
                ('surface', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('sp_s_unit', models.CharField(blank=True, max_length=30, null=True)),
                ('sp_u_conv', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('have_lb', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'gf_stockcode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GfStockgroup',
            fields=[
                ('stockgroup', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, null=True)),
                ('header_table', models.TextField(blank=True, null=True)),
                ('metal_fg', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'gf_stockgroup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modelpicbytea',
            fields=[
                ('item_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('image_data', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'modelpicbytea',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MtColor',
            fields=[
                ('mt_color', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('mt_desc', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'mt_color',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MtGroup',
            fields=[
                ('mt_group', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('mt_desc', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'mt_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MtMetal',
            fields=[
                ('mt_metal', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('mt_desc', models.CharField(blank=True, max_length=90, null=True)),
                ('mt_cal', models.CharField(blank=True, max_length=3, null=True)),
                ('mt_multi', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('mt_add', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('mt_pure', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('mt_alloy', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('alloy_date', models.DateTimeField(blank=True, null=True)),
                ('old_alloy', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('mt_show', models.CharField(blank=True, max_length=3, null=True)),
                ('mt_925tf', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'mt_metal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plating',
            fields=[
                ('plating', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('surf', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'plating',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlatType',
            fields=[
                ('plat_type', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('micron', models.DecimalField(decimal_places=2, max_digits=8)),
                ('surf', models.CharField(max_length=1)),
                ('remark', models.TextField(blank=True, null=True)),
                ('remarkpr', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'plat_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProBom',
            fields=[
                ('stock_id', models.BigIntegerField()),
                ('qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('route_seq_id', models.BigIntegerField(blank=True, null=True)),
                ('bomdata_id', models.AutoField(primary_key=True, serialize=False)),
                ('seq', models.CharField(blank=True, max_length=3, null=True)),
                ('wax_fg', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'pro_bom',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProCoat',
            fields=[
                ('pro_code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('plat_type', models.CharField(max_length=30)),
                ('remark', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pro_coat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProMetal',
            fields=[
                ('pro_code', models.CharField(blank=True, max_length=80, primary_key=True, serialize=False)),
                ('mt_metal', models.CharField(max_length=3)),
                ('sub_metal', models.CharField(max_length=3)),
                ('true_wt', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('std_conv_wt', models.DecimalField(decimal_places=2, max_digits=8)),
                ('wax_wt', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fin_wt', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('lastkey', models.DateTimeField()),
                ('lastuser', models.CharField(max_length=30)),
                ('cus_wt', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('cast_wt', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('mt_cast', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'pro_metal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProMetalbase',
            fields=[
                ('pro_code', models.CharField(max_length=30)),
                ('mt_metal', models.CharField(max_length=30)),
                ('lastkey', models.DateTimeField()),
                ('lastuser', models.CharField(max_length=30)),
                ('pro_metal_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'pro_metalbase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProMetalbom',
            fields=[
                ('pro_metal_id', models.CharField(max_length=30)),
                ('stock_id', models.CharField(max_length=30)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('route_seq_id', models.IntegerField(blank=True, null=True)),
                ('bomdata_id', models.AutoField(primary_key=True, serialize=False)),
                ('semi_char', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'pro_metalbom',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProRingsize',
            fields=[
                ('ring_size', models.CharField(max_length=5)),
                ('pro_code', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'pro_ringsize',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProRoutegroup',
            fields=[
                ('pro_code', models.CharField(max_length=9)),
                ('routegroup', models.CharField(max_length=2)),
                ('base_sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=80, null=True)),
                ('complete', models.CharField(blank=True, max_length=1, null=True)),
                ('complete_date', models.DateTimeField(blank=True, null=True)),
                ('complete_user', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'pro_routegroup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProSemi',
            fields=[
                ('semi_code', models.CharField(blank=True, max_length=80, primary_key=True, serialize=False)),
                ('semi_char', models.CharField(max_length=1)),
                ('cast_metal', models.CharField(blank=True, max_length=3, null=True)),
                ('pro_code', models.CharField(max_length=30)),
                ('routegroup', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'pro_semi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProSub',
            fields=[
                ('pro_code', models.CharField(blank=True, max_length=80, null=True)),
                ('pro_sub', models.CharField(max_length=2)),
                ('mt_metal', models.CharField(max_length=3)),
                ('description', models.CharField(blank=True, max_length=80, null=True)),
                ('pro_sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('metal_check', models.CharField(blank=True, max_length=1, null=True)),
                ('metal_checkdate', models.DateTimeField(blank=True, null=True)),
                ('metal_checkuser', models.CharField(blank=True, max_length=30, null=True)),
                ('routegroup', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'pro_sub',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProType',
            fields=[
                ('pro_type', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('desc_en', models.CharField(blank=True, max_length=30, null=True)),
                ('unit_en', models.CharField(max_length=3)),
                ('desc_th', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_th', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'pro_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SemiRouteId',
            fields=[
                ('semi_route_id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.CharField(max_length=1)),
                ('complete', models.CharField(blank=True, max_length=1, null=True)),
                ('complete_date', models.DateTimeField(blank=True, null=True)),
                ('complete_user', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'semi_route_id',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wfcust',
            fields=[
                ('cus_id', models.AutoField(primary_key=True, serialize=False)),
                ('cus_code', models.CharField(max_length=10, unique=True)),
                ('cus_com', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'wfcust',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gfmaster',
            fields=[
                ('pro_code', models.CharField(max_length=9, primary_key=True, serialize=False, unique=True)),
                ('std_925_wt', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('mold_wt', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('mold_metal', models.CharField(blank=True, max_length=3, null=True)),
                ('search_tag1', models.TextField(blank=True, null=True)),
                ('search_tag2', models.TextField(blank=True, null=True)),
                ('search_tag3', models.TextField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('surface', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('hallmark', models.IntegerField(blank=True, null=True)),
                ('route_check', models.CharField(blank=True, max_length=1, null=True)),
                ('route_checkdate', models.DateTimeField(blank=True, null=True)),
                ('route_checkuser', models.CharField(blank=True, max_length=30, null=True)),
                ('pd_gd', models.CharField(blank=True, max_length=2, null=True)),
                ('route_remark', models.TextField(blank=True, null=True)),
                ('sale_remark', models.TextField(blank=True, null=True)),
                ('mold_type', models.CharField(blank=True, max_length=2, null=True)),
                ('mold_model', models.CharField(blank=True, max_length=9, null=True)),
                ('cus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='setting_register.wfcust')),
                ('pro_type', models.ForeignKey(db_column='pro_type', on_delete=django.db.models.deletion.DO_NOTHING, to='setting_register.protype')),
            ],
            options={
                'db_table': 'gfmaster',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('setting', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=80, null=True)),
                ('sh_desc', models.CharField(blank=True, max_length=10, null=True)),
                ('lastuser', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'setting',
            },
        ),
        migrations.CreateModel(
            name='ProSpec',
            fields=[
                ('pro_code', models.OneToOneField(db_column='pro_code', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='setting_register.gfmaster')),
                ('pd_spec', models.TextField(blank=True, null=True)),
                ('lastkey', models.DateTimeField()),
                ('lastuser', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'pro_spec',
                'managed': False,
            },
        ),
    ]
